### ISSUE TITLE
Git-lfs error

### ISSUE THREAD

**Issue by rnakato** [danielchang2002/deepdep_reanalysis#1]
Thank you for sharing this interesting analysis. I tried to clone this repository but was unable to download the input data with the following error. The same error occurred on Google Colab as well, so I can't proceed with the analysis. I'd appreciate it if you could share the data elsewhere.

> git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/danielchang2002/deepdep_reanalysis.git/info/lfs'

**Comment by danielchang2002** [comment]
Hi @rnakato the data should be accessible now, just freed up some of my LFS quota :)

**Comment by rnakato** [comment]
Dear Daniel,

I was able to access it. Thank you so much!
